// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/insight': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/insight.get').default>>>>
    }
    '/api/kantong': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kantong.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kantong.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kantong.put').default>>>>
    }
    '/api/kantong/status': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kantong/status.put').default>>>>
    }
    '/api/kategori': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kategori.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kategori.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kategori.put').default>>>>
    }
    '/api/kategori/status': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kategori/status.put').default>>>>
    }
    '/api/laporan': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/laporan.get').default>>>>
    }
    '/api/pengaturan/apikey': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pengaturan/apikey.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pengaturan/apikey.post').default>>>>
    }
    '/api/profile/ganti-pin': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/ganti-pin.post').default>>>>
    }
    '/api/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/index.get').default>>>>
    }
    '/api/profile/update': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/update.put').default>>>>
    }
    '/api/referensi': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/referensi.get').default>>>>
    }
    '/api/transaksi': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transaksi.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transaksi.post').default>>>>
    }
    '/api/transaksi/quick-inputs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transaksi/quick-inputs.get').default>>>>
    }
    '/api/users/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/create.post').default>>>>
    }
    '/api/users/delete': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/delete.delete').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
    }
    '/api/users/update': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/update.put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}